---
- name: Install php-fpm and deps
  apt: name={{ item }} state=installed
  with_items:
    - php
    - php-fpm
    - php-mbstring
    - php-mysql
    - php-gd
    - php-xml

- name: Ensure php-fpm cgi.fix_pathinfo=0
  lineinfile: dest=/etc/php/7.0/fpm/php.ini regexp='^(.*)cgi.fix_pathinfo=' line=cgi.fix_pathinfo=0
  notify:
    - restart php7.0-fpm