- hosts: all
  become: yes
  gather_facts: no
  pre_tasks:
    - name: 'install python'
      raw: sudo apt-get -y install python-minimal python-apt

# DB
# https://github.com/jesusch/ansible-galera
- hosts: percona_cluster
  become: true
  roles:
    - percona_cluster

# web
- hosts: web
  become: true
  roles:
    - php-fpm
    - nginx

# glusterfs
# https://www.jeffgeerling.com/blog/simple-glusterfs-setup-ansible
- hosts: gluster
  become: true
  roles:
    - glusterfs
