- hosts: all
  become: yes
  gather_facts: no
  pre_tasks:
    - name: 'install python'
      raw: sudo apt-get -y install python-minimal python-apt

# DB
# https://github.com/morganchristiansson/ansible-galera
- hosts: percona_cluster
  become: true
  roles:
    - percona_cluster

# web
- hosts: web
  become: true
  roles:
    - php-fpm
    - nginx
    - glusterfs

- include: glusterfs_volumes.yml
