---
# - debug: msg="{{ hostvars[inventory_hostname].ansible_enp0s8.ipv4.address }}  {{ ansible_enp0s8.ipv4.address }}"
- include: repo.yml
- include: install_galera.yml
- include: firewall.yml
- include: grants.yml
- include: configure_galera.yml
- include: clustercheck.yml